# Base configs
baseurl: "http://buggitt.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Tanner Watrous"
subtitle: "Photos!"
author: "Tanner Watrous"
header:
 title: "Photography"
 subtitle: "by Tanner Watrous"
footer:
 name: "Hey there"
 bio: ""
 github: ""
web_design: "AJ"
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
